# -*- coding: utf-8 -*-
"""meu_chat_bot_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/112zSjR3IDLq1aUYGWOKc4xsvCDYI5NQx
"""

from flask import Flask, render_template, request
import os
import openai

app = Flask(__name__)

# Lê a chave das variáveis de ambiente
CHAVE_API = os.getenv("OPENROUTER_API_KEY")

client = openai.OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=CHAVE_API
)

MODELO = "nvidia/nemotron-3-ultra-550b-a55b:free"

@app.route("/", methods=["GET", "POST"])
def index():
    resposta = ""

    if request.method == "POST":
        pergunta = request.form.get("pergunta")

        if pergunta:
            try:
                completion = client.chat.completions.create(
                    model=MODELO,
                    messages=[
                        {"role": "user", "content": pergunta}
                    ]
                )

                resposta = completion.choices[0].message.content

            except Exception as e:
                resposta = f"Erro: {e}"

    return render_template("index.html", resposta=resposta)

if __name__ == "__main__":
    app.run(debug=True)